# Generated by Django 6.1.1 on 2026-09-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Sci-Fi', 'Sci-Fi'), ('History', 'History')], max_length=100),
        ),
    ]
